version: "3"

services: 
  nestjs_cnab400:
    build: .
    command: npm run start:dev
    ports: 
      - "3004:3000"
    volumes: 
      - .:/opt/docker_files/nestjs-cnab400
      - /opt/docker_files/nestjs-cnab400/node_modules